create table appUser (
    id integer generated by default as identity primary key,
    username varchar(128),
    password varchar(128),
    firstname varchar(128),
    surname varchar(128)
);

insert into appUser(id, username, password, firstname, surname)
values 
(default, 'davide', 'FPW', 'Davide', 'Spano'),
(default, 'giovanni', 'nuovo', 'Giovanni', 'Nuovo'),
(default, 'tizio', 'caio', 'Tizio', 'Caio');


create table form(
    id integer generated by default as identity primary key,
    title varchar(128),
    user_id integer,
    foreign key (user_id) references appUser(id)
);

create table question(
    id integer generated by default as identity primary key,
    title varchar(128),
    form_id integer,
    qType integer,
    qOrder integer,
    foreign key (form_id) references form(id)
);

create table qOption(
    id integer generated by default as identity primary key,
    oValue varchar(128),
    question_id integer,
    foreign key (question_id) references question(id)
);

insert into form (id, title, user_id)
values (default, 'Form di prova', 1);

select * from form;

insert into question (id, title, qType, qOrder, form_id)
values (default, 'Quanti anni hai?', 1, 1, 1),
       (default, 'Genere', 2, 0, 1);

select * from question;

insert into qOption (id, oValue, question_id)
values (default, 'Et&agrave;', 1),
       (default, 'Uomo', 2),
       (default, 'Donna', 2);

insert into qOption (id, oValue, question_id)
values (default, 'Et&agrave;', 3),
       (default, 'Uomo', 5),
       (default, 'Donna', 6);

insert into form (id, title, user_id)
values (default, 'Secondo form', 1),
       (default, 'Terzo form', 1);

insert into qOption (id, oValue, question_id)
values (default, 'default', 1);

insert into question (id, title, qType, qOrder, form_id)
values (default, 'Domanda di default', 1, 1, 2),
       (default, 'Domanda di default', 1, 1, 3);

select form.id as formId, form.title as formTitle, 
       form.USER_ID as formUserId,
       question.id as questionId, question.TITLE as questionTitle,
       question.FORM_ID as questionFormId, question.QTYPE as questionQType,
       question.QORDER as questionQOrder, qOption.id as optionId,
       qOption.OVALUE as optionValue, 
       qOption.QUESTION_ID as optionQuestionId
from form 
join question on form.id = question.FORM_ID 
join qOption on qOption.QUESTION_ID = question.id
where form.USER_ID = 1;