create table appUser (
    id integer generated by default as identity primary key,
    username varchar(128),
    password varchar(128),
    firstname varchar(128),
    surname varchar(128)
);

insert into appUser(id, username, password, firstname, surname)
values 
(default, 'davide', 'FPW', 'Davide', 'Spano'),
(default, 'giovanni', 'nuovo', 'Giovanni', 'Nuovo'),
(default, 'tizio', 'caio', 'Tizio', 'Caio');